# Generated by Django 6.0.2 on 2026-03-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalentry",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="historical_images/"
            ),
        ),
        migrations.AlterField(
            model_name="historicalentry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
