# Generated by Django 6.0.2 on 2026-03-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_historicalentry_image_alter_historicalentry_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalentry",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
