# Generated by Django 6.0.2 on 2026-03-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_historicalentry_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalentry",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
